services:
  - type: web
    name: private-llm
    env: docker
    repo: https://github.com/Alex-415/localLLM
    branch: main
    autoDeploy: true
    buildCommand: docker build -t private-llm .
    startCommand: node server/index.mjs
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://localllm.onrender.com
      - key: BASE_URL
        value: https://localllm.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: VITE_FIREBASE_MEASUREMENT_ID
        sync: false
    healthCheckPath: /api/health
    plan: starter
    numInstances: 1