services:
  - type: web
    name: private-llm
    env: docker
    repo: https://github.com/Alex-415/localLLM
    branch: main
    autoDeploy: true
    buildCommand: docker build -t private-llm .
    startCommand: docker run -p 10000:10000 -e NODE_ENV=production private-llm
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    plan: starter
    numInstances: 1