services:
  - type: web
    name: kml-production
    env: node
    buildCommand: |
      # Install root dependencies
      npm install --legacy-peer-deps
      
      # Build frontend
      npm run build
      
      # Install server dependencies
      cd server
      npm install --legacy-peer-deps
      cd ..
    startCommand: cd server && NODE_ENV=production node --experimental-modules index.mjs
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BASE_URL
        value: https://localllm.onrender.com
      - key: VITE_API_URL
        value: https://localllm.onrender.com
      - key: TOGETHER_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: VITE_FIREBASE_MEASUREMENT_ID
        sync: false
    healthCheckPath: /api/health
    plan: starter
    numInstances: 1