services:
  - type: web
    name: fullstack-chatbot
    env: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    branch: main
    autoDeploy: true
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false