services:
  - type: web
    name: private-llm-backend
    env: docker
    repo: https://github.com/Alex-415/localLLM
    branch: main
    autoDeploy: true
    buildCommand: cd server && docker build -t private-llm-backend .
    startCommand: docker run -p 4000:4000 -e NODE_ENV=production private-llm-backend
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/health
    plan: starter
    numInstances: 1

  - type: web
    name: private-llm-frontend
    env: docker
    repo: https://github.com/Alex-415/localLLM
    branch: main
    autoDeploy: true
    buildCommand: docker build -t private-llm-frontend .
    startCommand: docker run -p 80:80 private-llm-frontend
    envVars:
      - key: VITE_API_URL
        value: https://private-llm-backend.onrender.com
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: VITE_FIREBASE_MEASUREMENT_ID
        sync: false
    plan: starter
    numInstances: 1